### ISSUE TITLE
Obstruction data

### ISSUE THREAD

**Issue by test1230-lab** [multimedia-eurecat/ELFW#4]
Could you provide the hands/glasses/masks used in the augmentation?

**Comment by valillon** [comment]
I find _Issues_ more appropriate for discussions about code development.
For these kind of questions I kindly request to use the contact details provided in the [ELFW Project Site](https://multimedia-eurecat.github.io/2020/06/22/extended-faces-in-the-wild.html).
Since you already emailed me, let me use that means of communication.

**Comment by test1230-lab** [comment]
Sounds good to me.

**Comment by test1230-lab** [comment]
Hello again. I received you email and responded. I am unsure if you have received my follow up.
